### ISSUE TITLE
Apache libcloud support?

### ISSUE THREAD

**Issue by tfmorris** [oracle/bmcs-python-sdk#15]
Now that there's a Python SDK, any chance that it'll be used to build BMCS providers for Apache libcloud? Compute & Object Storage services would be of particular interest.

**Comment by craigcarl-oracle** [comment]
@tfmorris libcloud is on our radar but there aren't any timelines attached to it. I'd like to understand more about the general use case, please get in touch; craig.carl@oracle.com.

**Comment by nbtest123** [comment]
Is there any update on this wrt oraclecloud support in apache libcloud ?

thanks
