### ISSUE TITLE
load balancer support

### ISSUE THREAD

**Issue by jhorwit2** [oracle/bmcs-python-sdk#17]

**Comment by jodoglevy** [comment]
Working on it. Expect something soon :)

**Comment by jodoglevy** [comment]
Added in https://github.com/oracle/bmcs-python-sdk/commit/1074435e1e7a02d134aafe13dd91230c105d5edb and released in version [1.3.3](https://github.com/oracle/bmcs-python-sdk/releases/tag/v1.3.3)
