### ISSUE TITLE
Need a supported mechanism for a streaming upload to object storage.

### ISSUE THREAD

**Issue by brunson** [oracle/bmcs-python-sdk#23]
I'm writing a client to move our data from AWS S3 to BMCS Object Storage.  

I ran into an issue with the underlying version of requests you have pinned.  I'm able to get to the stream of the AWS download from their SDK, however in order for it to be handled correctly as a stream and not a file I had to do some wrapping of the stream object to "fool" requests into doing the right thing.  This is due to their mechanism of inferring whether the object passed in is a file handle or a stream.  My method relies in internal knowledge of the requests implementation and, having looked at the newer sources, I'm can see it will will definitely break when you move to a more recent version of requests.

I think it's a better idea to expose something in the BMCS SDK to explicitly indicate that it's being passed a stream object and then handle the calls to requests appropriately to assure it's handled correctly.  If we discuss what you think it the appropriate interface and reach a design statement, I can submit a patch for your review to implement it.

**Comment by mross22** [comment]
Can you give some more details on what wrapping you have to do in order to 'fool' requests into thinking it is a stream and what the stream-like object looks like that you are getting back from the AWS SDK?  I think I understand the problem you're getting at but ideally we wouldn't have to add any code in our SDK that is based on requests internals.  Regardless of where the wrapping code goes it would be nice if it was done in a way more explicitly supported by requests as opposed to being dependent on their internal implementation.

**Comment by brunson** [comment]
Take a look at this code in the requests package at the version you have pinned (https://github.com/requests/requests/blob/v2.11.1/requests/models.py#L472)

You can see that requests is trying to infer if the object it received is file-like in order to get the content-length.  If the object has a seek and a tell attribute it assumes it can seek to the end of the file to get the length.  The AWS client response from boto2.Client('s3').get_object() includes a Body with a _raw_stream attribute which can be read() from.  However, it also has seek() and tell() methods, but the seek() method throws an exception if called to the tune of "method unimplemented".  

We tried several other ways of passing in the AWS response, but they all either failed or else succeeded in seek()ing to the end of the "file" and reading the entire content into memory.  This is prohibitive since we're trying to move files in excess of 20GB at times.

My workaround was to runtime patch the seek to a No Op lambda, then to patch the tell() method with a class that will return zero the first time it is __call__()'ed and the actual value of the Content-Length retrieved from the AWS client subsequently.  This is what I mean by "fooling" the requests module into getting the correct content length without actually reading the entire body of the response into memory.

The underlying issue is in the requests module and its mechanism of inferring the capabilities of the object it's passed.  Perhaps it won't fail in this manner when you move to more recent releases as the implementation has changed considerably, but this seems like an obvious place where we need to be interacting with the requests API in a manner that can reliably stream data without having to store it locally.

I'd like to hear your thoughts on the matter.

**Comment by brunson** [comment]
@mross22 Thanks for the assistance. 

In summary, your recommendation of wrapping the AWS request in a class that hides the seek() and tell() methods is a bit cleaner than my solution.  Looking at the super_len() function of requests as us suggested also indicates that defining len() or __len__() in the class will also cause requests to properly fetch the content-length without trying to read the entire stream into memory.

I appreciate your help in finding a more reliable work around.

Thanks,
e.
